stages:
  - sonar-check
  - skip-sonar-check
  
sonar-check:
  stage: sonar-check
  image: sonarsource/sonar-scanner-cli:5.0.1
  variables:
    SONAR_TOKEN: $SONAR_TOKEN
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.projectKey=${CI_PROJECT_NAME} -Dsonar.sources=. -Dsonar.qualitygate.wait=true -Dsonar.host.url=https://sonarqube.roche.com -Dsonar.login=$SONAR_LOGIN

  only:
    refs:
        - merge_requests
    variables:
        - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^develop-.*$/ || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"

skip-sonar-check:
  stage: skip-sonar-check
  script: 
    - echo "pipeline success"
  only:
    refs:
        - merge_requests
    variables: 
       - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME !~ /^develop-.*$/ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "develop" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "main" 
       